### PR TITLE
Fixed issue with incorrect date values

### LINKED ISSUE #237: Calendar causes crash on Firefox
@blcham 
In form 1, domain specific questions, `RangeError: Invalid time value` happens causing crash. This happens only in Firefox, not Chrome.

### PR DESCRIPTION
**Pull request by LaChope**
Resolves #237

### CODE REVIEW

File: src/components/answer/TypeaheadAnswer.jsx [hunk 1]
```diff
@@ -14,7 +14,7 @@ import { IntelligentTreeSelect } from "intelligent-tree-select/lib/components/In
 import "intelligent-tree-select/lib/styles.css";
 
 const processTypeaheadOptions = (options, intl) => {
-  if (!options) {
+  if (!options || !options.length) {
```
Comment (LaChope) [inline src/components/answer/TypeaheadAnswer.jsx:17]: Committed by accident, should be part of #236
