### PR TITLE
Fix query of possible values

### LINKED ISSUE #270: Fix react 18 s-forms in record-manager-ui
@blcham 
In record-manager-ui, when using s-forms with React 18, the form can't be loaded because of jsonld error. This error is thrown only with forms querying possible values.

This is **not** due to `react-datepicker` as it was removed from the form.

Image

### PR DESCRIPTION
**Pull request by LaChope**
Resolves #270.
Also tested in record-manager-ui.

### CODE REVIEW

File: src/model/FormGenerator.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ export default class FormGenerator {
    *
    * @return Promise with generated form definition and form data
    */
-  static constructForm(structure, intl) {
+  static async constructForm(structure, intl) {
```
Comment (blcham) [inline src/model/FormGenerator.js:32]: I guess the comment of this method is not relevant anymore.

Comment (LaChope) [reply src/model/FormGenerator.js:32]: I need to find the appropriate semantic but this is still appropriate, is is doing the same thing as before, just the dependency was bumped and so the implementation had to be changed, but the functionality remains the same
